name: Publish Van

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "PKG_VERSION=v$VERSION" >> $GITHUB_ENV

    - name: Setup Pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: 9.12.3

    - name: Cache
      id: cache
      uses: actions/cache@v4.2.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: pnpm install

    - name: Build
      run: pnpm run build-prod && npx vsce package --no-dependencies

    - name: Publish
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      run: npx vsce publish -p $VSCE_TOKEN --no-dependencies

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create new tag
      run: git tag -a $PKG_VERSION -m "release $PKG_VERSION"

    - name: Push Tag
      run: git push origin $PKG_VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自动注入的权限令牌
